// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IGinService is an autogenerated mock type for the IGinService type
type IGinService struct {
	mock.Mock
}

// ChatHandler provides a mock function with given fields: c
func (_m *IGinService) ChatHandler(c *gin.Context) {
	_m.Called(c)
}

// CopyHandler provides a mock function with given fields: c
func (_m *IGinService) CopyHandler(c *gin.Context) {
	_m.Called(c)
}

// CreateBlobHandler provides a mock function with given fields: c
func (_m *IGinService) CreateBlobHandler(c *gin.Context) {
	_m.Called(c)
}

// CreateHandler provides a mock function with given fields: c
func (_m *IGinService) CreateHandler(c *gin.Context) {
	_m.Called(c)
}

// DeleteHandler provides a mock function with given fields: c
func (_m *IGinService) DeleteHandler(c *gin.Context) {
	_m.Called(c)
}

// EmbedHandler provides a mock function with given fields: c
func (_m *IGinService) EmbedHandler(c *gin.Context) {
	_m.Called(c)
}

// EmbeddingsHandler provides a mock function with given fields: c
func (_m *IGinService) EmbeddingsHandler(c *gin.Context) {
	_m.Called(c)
}

// GenerateHandler provides a mock function with given fields: c
func (_m *IGinService) GenerateHandler(c *gin.Context) {
	_m.Called(c)
}

// HeadBlobHandler provides a mock function with given fields: c
func (_m *IGinService) HeadBlobHandler(c *gin.Context) {
	_m.Called(c)
}

// HomeHandler provides a mock function with given fields: c
func (_m *IGinService) HomeHandler(c *gin.Context) {
	_m.Called(c)
}

// ListHandler provides a mock function with given fields: c
func (_m *IGinService) ListHandler(c *gin.Context) {
	_m.Called(c)
}

// PsHandler provides a mock function with given fields: c
func (_m *IGinService) PsHandler(c *gin.Context) {
	_m.Called(c)
}

// PullHandler provides a mock function with given fields: c
func (_m *IGinService) PullHandler(c *gin.Context) {
	_m.Called(c)
}

// PushHandler provides a mock function with given fields: c
func (_m *IGinService) PushHandler(c *gin.Context) {
	_m.Called(c)
}

// ShowHandler provides a mock function with given fields: c
func (_m *IGinService) ShowHandler(c *gin.Context) {
	_m.Called(c)
}

// VersionHandler provides a mock function with given fields: c
func (_m *IGinService) VersionHandler(c *gin.Context) {
	_m.Called(c)
}

// NewIGinService creates a new instance of IGinService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGinService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGinService {
	mock := &IGinService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
