
name: Build and publish docker images
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: set release date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ vars.DOCKERHUB_USERNAME }}/gollamas
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      env:
        VERSION: ${{ steps.meta.outputs.version }}
        COMMIT_SHA: ${{github.sha}}
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/riscv64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        buildargs: VERSION COMMIT_SHA RELEASE_DATE
