
name: Release binary
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set release date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ vars.DOCKERHUB_USERNAME }}/gollamas
          ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker images
      id: docker_build
      uses: docker/build-push-action@v6
      env:
        VERSION: ${{ steps.meta.outputs.version }}
        COMMIT_SHA: ${{github.sha}}
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/riscv64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        buildargs: VERSION COMMIT_SHA RELEASE_DATE

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: index.docker.io/${{ vars.DOCKERHUB_USERNAME }}/gollamas
        subject-digest: ${{ steps.docker_build.outputs.digest }}
        push-to-registry: true
